POST http://localhost:3333/courses
Content-Type: application/json

{
    "title": "Curso de Docker"
}

###

GET http://localhost:3333/courses

###

GET http://localhost:3333/courses/9ad18aa1-9ecf-4920-b1a5-9e0d9cc5f191
